modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tinutils"
version = "${version}"
displayName = "tinutils"
authors = "randomusert"
description = '''
A util mod for minecraft making it easier or harder
'''
#logoFile = ""

[[dependencies.tinutils]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinutils]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinutils]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.tinutils]]
modId = "jei"
type = "required"
versionRange = "[19.27.0.340,)"
ordering = "AFTER"
side = "BOTH"


[[mixins]]
config = "tinutils.mixins.json"
